/**
 * Freezes the grade-stability corpus from the BUILT package.
 *
 *   pnpm --filter @intellectif/lk-core build
 *   node scripts/generate-vectors.mjs                       # add new vectors only
 *   node scripts/generate-vectors.mjs --accept-grade-change # also rewrite existing ones
 *
 * Adding a case is routine and needs no flag. Changing or removing an existing
 * expectation is refused unless `--accept-grade-change` is passed, and the ids
 * that would change are printed either way. That refusal is the point of this
 * script: a vector that no longer matches means a stored grade would come out
 * differently today, and "regenerate until it is green" is the one habit that
 * would quietly turn this gate into a formality. If you pass the flag, the
 * change it records is a package MAJOR (docs/roadmap.md, standing decisions).
 *
 * Rewording a vector's `note` needs no flag: only the call and its frozen
 * result are compared.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CORPUS_VERSION, callVector, canonical, encode } from '../vectors/replay.mjs';
import { CASES } from './vector-cases.mjs';

const require = createRequire(import.meta.url);
const PKG_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = join(PKG_ROOT, '..', '..');
const CORPUS = join(PKG_ROOT, 'vectors', 'scoring.json');
const accept = process.argv.includes('--accept-grade-change');

const core = require(join(PKG_ROOT, 'dist', 'index.cjs'));
const { version } = JSON.parse(readFileSync(join(PKG_ROOT, 'package.json'), 'utf8'));

const seen = new Set();
for (const entry of CASES) {
  if (seen.has(entry.id)) throw new Error(`Duplicate vector id: ${entry.id}`);
  seen.add(entry.id);
}

/** Sorts keys at every depth so the file diffs cleanly across refactors. */
const sortKeys = (value) =>
  Array.isArray(value)
    ? value.map(sortKeys)
    : value !== null && typeof value === 'object'
      ? Object.fromEntries(
          Object.keys(value)
            .sort()
            .map((key) => [key, sortKeys(value[key])]),
        )
      : value;

const fresh = CASES.map((entry) => {
  const vector = {
    id: entry.id,
    ...(entry.const !== undefined
      ? { const: entry.const }
      : { fn: entry.fn, args: entry.args.map(encode) }),
    ...(entry.ignore ? { ignore: entry.ignore } : {}),
    ...(entry.note ? { note: entry.note } : {}),
  };
  const expect = callVector(core, vector);
  if (expect?.$missing !== undefined) {
    throw new Error(`${entry.id}: the built package does not export ${expect.$missing}`);
  }
  return sortKeys({ ...vector, expect });
});

const previous = existsSync(CORPUS) ? JSON.parse(readFileSync(CORPUS, 'utf8')) : { vectors: [] };
const before = new Map(previous.vectors.map((vector) => [vector.id, vector]));
const after = new Map(fresh.map((vector) => [vector.id, vector]));

// Only what decides a grade is compared: the call and its frozen result. A
// `note` is prose for the next reader. Rewording one must not demand the flag
// that exists for grade changes, or reaching for that flag becomes routine.
const gradeShape = (vector) =>
  canonical({
    fn: vector.fn ?? null,
    const: vector.const ?? null,
    args: vector.args ?? null,
    ignore: vector.ignore ?? null,
    expect: vector.expect,
  });
const changed = fresh.filter(
  (vector) => before.has(vector.id) && gradeShape(before.get(vector.id)) !== gradeShape(vector),
);
const renoted = fresh.filter(
  (vector) =>
    before.has(vector.id) &&
    gradeShape(before.get(vector.id)) === gradeShape(vector) &&
    before.get(vector.id).note !== vector.note,
);
const removed = [...before.keys()].filter((id) => !after.has(id));
const added = fresh.filter((vector) => !before.has(vector.id));

for (const vector of changed) console.log(`CHANGED  ${vector.id}`);
for (const id of removed) console.log(`REMOVED  ${id}`);
for (const vector of added) console.log(`added    ${vector.id}`);
for (const vector of renoted) console.log(`note     ${vector.id}`);

if ((changed.length > 0 || removed.length > 0) && !accept) {
  console.error(
    `\nRefusing to write: ${changed.length} existing vector(s) changed and ${removed.length} removed.\n` +
      'A changed expectation means a stored grade would score differently. If that is intended, it is a\n' +
      'package major: rerun with --accept-grade-change and say so in the changeset.',
  );
  process.exit(1);
}

const corpus = sortKeys({
  $comment:
    'Grade-stability corpus for @intellectif/lk-core. Generated by scripts/generate-vectors.mjs from the built ' +
    'package; never edit expectations by hand. Replay with vectors/replay.mjs. See vectors/README.md.',
  corpusVersion: CORPUS_VERSION,
  frozenFrom: `@intellectif/lk-core@${version}`,
  vectors: fresh,
});

// JSON.stringify leaves non-ASCII characters literal, so a no-break space, a
// combining accent and a composed accent would be invisible in review, which is
// exactly where a reviewer needs to see them. Every non-ASCII code unit is
// escaped.
const text = `${JSON.stringify(corpus, null, 2).replace(
  /[-￿]/g,
  (char) => `\\u${char.charCodeAt(0).toString(16).padStart(4, '0')}`,
)}\n`;
writeFileSync(CORPUS, text);

// Hand the layout to the repo formatter so `biome check` agrees with the file.
// Invoked through Node rather than the `.bin` shim, which is a `.cmd` on
// Windows and cannot be spawned without a shell.
const biome = require.resolve('@biomejs/biome/bin/biome', { paths: [REPO_ROOT] });
execFileSync(process.execPath, [biome, 'format', '--write', CORPUS], { stdio: 'inherit' });

console.log(
  `\nWrote ${fresh.length} vectors (${added.length} new, ${changed.length} changed) to vectors/scoring.json`,
);
