export type {
  ActivityData,
  ActivityDataMap,
  ActivityResult,
  ActivityType,
  BlankConfig,
  FillInTheBlanksData,
  FillInTheBlanksLearnerResponse,
  InteractionEvent,
  LearnerResponse,
  MultipleChoiceData,
  MultipleChoiceLearnerResponse,
  MultipleChoiceOption,
  ScoringDetail,
  ScoringResult,
  ValidationError,
  ValidationResult,
} from './activity.js';
export type { ThemeTokens } from './theme.js';
export type {
  XAPIActor,
  XAPIConfig,
  XAPIContext,
  XAPIError,
  XAPIObject,
  XAPIResult,
  XAPIScore,
  XAPIStatement,
  XAPIVerbObject,
} from './xapi.js';
